### ISSUE TITLE
hello. something wrong when i run this project

### ISSUE THREAD

**Issue by yangye19960922** [ayaabdelsalam91/Input-Cell-Attention#1]
Hi, when i finish running trainModels.py and try to run saliency.py, an error occurs, it shows that _**RuntimeError: cudnn RNN backward can only be called in training mode**_
![image](https://user-images.githubusercontent.com/36871131/84356204-74512180-abf6-11ea-881e-2b4c4d4c0691.png)
could you please teach me how to solve this problem ?

**Comment by ayaabdelsalam91** [comment]
This can be solved by running this file on cpu instead of GPU getting the gradient for RNNs without training is currently not supported by cuda

**Comment by yangye19960922** [comment]
thanks for your reply，i add "model.train()"into demo， and it works



---Original---

**Comment by ayaabdelsalam91** [comment]
This will cause the weight of the model to update which is not something we want at this point

**Comment by yangye19960922** [comment]
> This will cause the weight of the model to update which is not something we want at this point

so you mean i need to run this file on cpu instead of adding 'model.train()' into file, becauce this operation will lead to wrong results?

**Comment by ayaabdelsalam91** [comment]
yes
